### ISSUE TITLE
TypeError thrown by sidebar TOC when accessing deleted page

### ISSUE THREAD

**Issue by pyuxiang** [ssahara/dw-plugin-toctweak#14]
When accessing a deleted page, i.e. by removing page contents, the following error message is thrown by PHP:

```
TypeError: Cannot access offset of type string on string

An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the toctweak plugin.

More info has been written to the DokuWiki error log.
```

<details><summary>Dump of Dokuwiki error log</summary>

```
2022-12-26 11:51:31     /var/www/dokuwiki/lib/plugins/toctweak/helper.php(96)   TypeError: Cannot access offset of type string on string
  #0 /var/www/dokuwiki/lib/plugins/toctweak/syntax/sidetoc.php(73): helper_plugin_toctweak->get_metatoc()
  #1 /var/www/dokuwiki/inc/parser/renderer.php(117): syntax_plugin_toctweak_sidetoc->render()
  #2 /var/www/dokuwiki/inc/parserutils.php(682): Doku_Renderer->plugin()
  #3 /var/www/dokuwiki/inc/parserutils.php(149): p_render()
  #4 /var/www/dokuwiki/inc/parserutils.php(89): p_cached_output()
  #5 /var/www/dokuwiki/inc/template.php(1585): p_wiki_xhtml()
  #6 /var/www/dokuwiki/lib/tpl/dokuwiki/main.php(43): tpl_include_page()
  #7 /var/www/dokuwiki/inc/actions.php(27): include('...')
  #8 /var/www/dokuwiki/doku.php(126): act_dispatch()
  #9 {main}
```

</details>

Cause seems to be due to `$INFO['meta']` array being unpopulated for such deleted pages,

> array(9) { ["date"]=> string(0) "" ["creator"]=> string(0) "" ["user"]=> string(0) "" ["last_change"]=> string(0) "" ["contributor"]=> string(0) "" ["title"]=> string(0) "" ["description"]=> string(0) "" ["relation"]=> string(0) "" ["internal"]=> string(0) "" } 

----

This issue does not manifest when the page itself has not been previously created, nor did it appear in Dokuwiki Hogfather running PHP 7.4 (Ubuntu 20.04).

Environment:

  * Plugin version 2.0.2 (2018-01-08)
  * Dokuwiki version 2022-07-31 "Igor"
  * PHP 8.1 (Ubuntu 22.04)

**Comment by pyuxiang** [comment]
Resolution is relatively straightfoward - replace the if-else condition in lines 95-99 of `$DOKUWIKI/lib/plugins/toctweak/helper.php`:

https://github.com/ssahara/dw-plugin-toctweak/blob/6fea3566234b5fbe9894d6abe407afe23d537454/helper.php#L95-L100

with just the else-clause from line 98:

```
$toc = p_get_metadata($id,'description tableofcontents'); 
```

When the `tableofcontents` variable is dynamically retrieved, the `$toc` will be assigned `null` and immediately exits the TOC render function. Not sure what side-effects there are, so leaving it as a comment.

**Comment by jmull9315** [comment]
Thank you for the issue report and suggested fix above. It was very helpful.

I was seeing the same issue, but the above fix was not complete for me. An AI identified (and provided a fix for) the same issue in rendertoc.php. The issue seems to have appeared after upgrading from PHP 7 to PHP 8.
 
Here is the AI generated description, with some edits by me:
 ----
The second patch needed was in `action/rendertoc.php` line 217, in `handleContentDisplay()`, triggered via the `TPL_CONTENT_DISPLAY` event during normal page rendering — not the sidebar/SIDETOC path described in the original report.

The root cause is the same: `$INFO['meta']['description']` is an empty string on deleted pages, and accessing `['tableofcontents']` on it throws a TypeError in PHP 8. The plugin also uses `@` suppression in `rendertoc.php`, but PHP 8 does not suppress TypeErrors with `@`.

There are three affected locations total:
- `helper.php` ~line 96 in `get_metatoc()` (the original report)
- `action/rendertoc.php` ~line 137 in `handlePostProcess()`
- `action/rendertoc.php` ~line 217 in `handleContentDisplay()`

Environment: DokuWiki "Librarian" 2025-05-14b, PHP 8.3.27, Ubuntu 22.04.5 LTS, plugin version 2.0.2.

This likely affects anyone who has moved from PHP 7 to PHP 8. PHP 7 silently returned null for string offset access with a non-numeric key; PHP 8 throws a TypeError.
----
AI generaed a patch for all three locations that works for me. I am really just a DokuWiki user and I'm not sure I should be posting AI generated code.

**Comment by jmull9315** [comment]
Ok, here is more info from the AI; it seems ok to me to post the snippets here.

**Fix:**

In `helper.php` line 96, replace:
```php
$toc = $INFO['meta']['description']['tableofcontents'];
```
with:
```php
$meta_desc = $INFO['meta']['description'];
$toc = is_array($meta_desc) ? ($meta_desc['tableofcontents'] ?? null) : null;
```

In `action/rendertoc.php` lines 137 and 217, replace both occurrences of:
```php
$toc = @$INFO['meta']['description']['tableofcontents'] ?: array();
```
with:
```php
$meta_desc = $INFO['meta']['description'];
$toc = (is_array($meta_desc) && isset($meta_desc['tableofcontents']))
     ? $meta_desc['tableofcontents'] : array();
```
